plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    id 'application'
    id 'java'
    id 'groovy'
}

repositories {
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation 'com.google.guava:guava:33.6.0-jre'

    testImplementation 'junit:junit:4.13.2'
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"

    // Spock mandatory dependencies
    implementation platform('org.apache.groovy:groovy-bom:5.0.2')
    implementation 'org.apache.groovy:groovy'
    testImplementation platform("org.spockframework:spock-bom:2.4-groovy-5.0")
    testImplementation "org.spockframework:spock-core"
    testImplementation "org.spockframework:spock-junit4"
    testImplementation "org.hamcrest:hamcrest-core:3.0"
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}

